apiVersion: v1
kind: Secret
metadata:
  name: demo-app-binding
type: Opaque
data:
  host: ZGVtby1wZy1jbHVzdGVyLW1hc3Rlci5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  port: NTQzMg==
  dbname: ZGVtbw==
  username: cG9zdGdyZXM=
  password: YUpIR3dTOGZ3RDVpb1pxTE9jV3l4dk1yS29qR2RJT3BRZ3FaaEl2alJ2Nm9RMGN0bTZGNGxJSUJzbU14M0I1Rg==
  sslmode: cmVxdWlyZQ==
