---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: a8s-instance-user-role
rules:
- apiGroups:
  - postgresql.anynines.com
  - backups.anynines.com
  - servicebindings.anynines.com
  resources:
  - postgresqls
  - backups
  - recoveries
  - servicebindings
  verbs:
  - list
  - watch
  - create
  - patch
  - get
  - delete
