apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
    spec:
      containers:
      - name: s3-app
        image: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/demo/s3-app:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
