apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: minio-config-script
  namespace: minio-dev
  files:
  - minio_config.sh
  options:
      disableNameSuffixHash: true

resources:
  - minio-config-job.yaml